In [1]:
from protosc import filter_model
from protosc.simulation import create_simulation_data, create_correlated_data
from protosc.filter_model import calc_chisquare
from protosc.final_selection import final_selection
from collections import defaultdict
import numpy as np

In [2]:
np.random.seed(1928374)
X, y, truth = create_correlated_data()

In [3]:
%%time
np.random.seed(9835)
feature_accuracy = filter_model(X, y, fold_seed=213874)

Wall time: 821 ms


In [4]:
for res in feature_accuracy:
    print(truth["clusters"][res[0]])

[9 9 9 9 9 6 6 6 6 6 8 8 8 8 8]
[8 8 8 8 8 9 9 9 9 9 7 7 7 7 7]
[8 8 8 8 8 6 6 6 6 6 7 7 7 7 7]
[8 8 8 8 8 9 9 9 9 9 6 6 6 6 6]
[8 8 8 8 8 9 9 9 9 9 6 6 6 6 6 7 7 7 7 7]
[8 8 8 8 8 9 9 9 9 9 6 6 6 6 6]
[8 8 8 8 8 9 9 9 9 9 6 6 6 6 6]
[8 8 8 8 8 9 9 9 9 9 6 6 6 6 6]


In [5]:
null_accuracy = defaultdict(lambda: [])
for _ in range(100):
    res = filter_model(X, y, fold_seed=213874, null_distribution=True)
    for i, val in enumerate(res):
        null_accuracy[i].append(val[1])
null_accuracy = list(null_accuracy.values())

In [6]:
feature_selection = final_selection(feature_accuracy, null_accuracy)

In [10]:
print(set(feature_selection)-set(truth["selected_features"]))

set()
