In [1]:
import numpy as np

from protosc.model import FilterModel
from protosc.model.filter import select_with_filter
from protosc.simulation import create_correlated_data
from protosc.model.final_selection import final_selection

In [2]:
np.random.seed(1928374)
X, y, truth = create_correlated_data()

In [3]:
%%time
np.random.seed(9835)
feature_accuracy = FilterModel().execute(X, y, fold_seed=213874)

CPU times: user 26.4 s, sys: 14.4 s, total: 40.8 s
Wall time: 22.6 s


In [4]:
for res in feature_accuracy:
    print(truth["clusters"][res["features"]])

[9 9 9 9 9 6 6 6 6 6 8 8 8 8 8 7 7 7 7 7]
[8 8 8 8 8 9 9 9 9 9 7 7 7 7 7 6 6 6 6 6]
[8 8 8 8 8 6 6 6 6 6 7 7 7 7 7 9 9 9 9 9]
[8 8 8 8 8 9 9 9 9 9 6 6 6 6 6 7 7 7 7 7]
[8 8 8 8 8 9 9 9 9 9 6 6 6 6 6 7 7 7 7 7]
[8 8 8 8 8 9 9 9 9 9 6 6 6 6 6 7 7 7 7 7]
[8 8 8 8 8 9 9 9 9 9 6 6 6 6 6 7 7 7 7 7]
[8 8 8 8 8 9 9 9 9 9 6 6 6 6 6 7 7 7 7 7]


In [5]:
feature_selection = select_with_filter(X, y, n_fold=8, n_jobs=-1)

100%|██████████| 101/101 [03:18<00:00,  1.97s/it]


In [6]:
print(set(feature_selection)-set(truth["selected_features"]))

set()
